name: Docker build phase

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Docker build process
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - 
        name: Log into dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build the dockerfile
        run: docker build . --file ./Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/first-gha-img:latest
      - name: Docker push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/first-gha-img:latest